<?php

/*
 * implements hook_menu
 */

function misc_menu() {
	module_load_include('inc', 'pathauto');

	$customnodes = array('news', 'news/latest', 'network-learning', 'network-learning/latest');

	foreach ($customnodes as $key)
		$items[$key] = array(
			'page callback' => 'theme_render_template',
			'page arguments' => array(path_to_theme() . '/templates/node-unformatted--' . pathauto_cleanstring($key) . '.tpl.php', array()),
			'access callback' => TRUE,
		);

	return $items;
}

/**
 * implements hook_form_alter
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function misc_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'nodequeue_arrange_subqueue_form_3') {
        $form['#validate'][] = 'validate_marquee_node_4_contains_vertical_image';
    }
}

/**
 * validation function to make sure that specified nodes in the marquee nodequeue have a vertical image to display instead
 * of a horizontal image
 *
 * Currently only checks the node in position 4
 *
 * form name may also change so watch for that
 * TODO: flag the positions that are vertical in the nodqueue form,
 * TODO: setup form name so that it can find the form if the name changes
 * name changes
 * @param $form
 * @param $form_state
 */
function validate_marquee_node_4_contains_vertical_image($form, &$form_state) {

    $node4_nid = (array_keys($form_state['input']['nodes']));
    $new_node_4 = node_load($node4_nid[3]);
    $does_node_4_have_vertical_image = sizeof($new_node_4->field_vertical_image) > 0;

    if (!$does_node_4_have_vertical_image) {
        form_set_error($name = nodequeue_arrange_subqueue_form_3, $message = 'Must add vertical image to node in position 4');
    }
}

/*
 * implements hook_entity_info_alter
 */

function misc_entity_info_alter(&$entity_info) {
	$entity_info['node']['view modes']['our_model'] = array(
		'label' => 'Our Model',
		'custom settings' => TRUE,
	);
}
