<?php

/*
 * implements hook_menu
 */

function misc_menu() {
    module_load_include('inc', 'pathauto');

    $customnodes = array('news', 'news/latest', 'network-learning', 'network-learning/latest', 'contact-thank-you');

    foreach ($customnodes as $key)
        $items[$key] = array(
            'page callback' => 'theme_render_template',
            'page arguments' => array(path_to_theme() . '/templates/node-unformatted--' . pathauto_cleanstring($key) . '.tpl.php', array()),
            'access callback' => TRUE,
        );

    return $items;
}

/*
 * implements hook_theme()
 */
function misc_theme() {
    return array(
        'misc_contact_form_email' => array(
            'template' => 'templates/contact_form_email',
            'arguments' => array('content' => null),
        ),
    );
}

/**
 * implements hook_form_alter
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function misc_form_alter(&$form, &$form_state, $form_id) {

    if($form_id == 'national_organization_node_form'){
        $form['field_national_organization_twit'][LANGUAGE_NONE][0]['#format'] = 'full_html';
    }

    if($form_id == 'nodequeue_arrange_subqueue_form_3') {
        $form['add']['#prefix'] = '<b>Please ensure that content in the 4th position has a vertical image.</b>';
        $form['#validate'][] = 'validate_marquee_node_4_contains_vertical_image';
    }
}

/**
 * validation function to make sure that specified nodes in the marquee nodequeue have a vertical image to display instead
 * of a horizontal image
 *
 * Currently only checks the node in position 4
 *
 * form name may also change so watch for that
 * TODO: flag the positions that are vertical in the nodqueue form,
 * TODO: setup form name so that it can find the form if the name changes
 * name changes
 * @param $form
 * @param $form_state
 */
function validate_marquee_node_4_contains_vertical_image($form, &$form_state) {

    $node4_nid = (array_keys($form_state['input']['nodes']));
    if(sizeof($node4_nid) > 3)
    {
        $new_node_4 = node_load($node4_nid[3]);
        $does_node_4_have_vertical_image = sizeof($new_node_4->field_vertical_image) > 0;

        if (!$does_node_4_have_vertical_image) {
            form_set_error($name = nodequeue_arrange_subqueue_form_3, $message = 'Content in position 4 must have a vertical image!');
        }
    }
}

/*
 * implements hook_entity_info_alter
 */

function misc_entity_info_alter(&$entity_info) {
    $entity_info['node']['view modes']['our_model'] = array(
        'label' => 'Our Model',
        'custom settings' => TRUE,
    );
    $entity_info['node']['view modes']['global_organization'] = array(
        'label' => 'Global organization',
        'custom settings' => TRUE,
    );
}

/*
 * contact us form
 */
function misc_widget_contact_form() {
    module_load_include('inc', 'misc', 'includes/misc_contact.form');
    return render(drupal_get_form('misc_contact_form'));
}

/*
 * implements hook_mail()
 */
function misc_mail($key, &$message, $params) {

    switch ($key) {
        case 'contact_form':
            $message['subject'] = t('Contact email from website');
            $langcode = $message['language']->language;
            $message['body'][] = theme('misc_contact_form_email', array('content' => $params));
            break;
    }
}


/**
 * Implements hook_block_info()
 * @author AlexB
 */
function misc_block_info()
{
    $blocks['contact_form'] = array(
        'info' => t('Contact form'),
        'status' => TRUE,
        'region' => 'content',
        'weight' => 0,
        'visibility' => 1,
    );

    return $blocks;
}

/**
 * Implements hook_block_view
 * @author AlexB
 */
function misc_block_view($delta = '')
{
    switch($delta){
        case 'contact_form':
            $block['title'] = '';
            $block['content'] = contact_block_contents($delta);
            return $block;
            break;
    }
}

/**
 * A module defined block content function.
 * @author AlexB
 */
function contact_block_contents($delta)
{
    switch($delta){
        case 'contact_form':
            $contact_form = misc_widget_contact_form();
            return $contact_form;
            break;
    }

}
