<?php

/*
 * implements hook_theme
 */
function widget_facebook_theme($existing, $type, $theme, $path) {
  return array(
    'widget_facebook_box' => array(
      'template' => 'templates/widget-facebook-box',
    ),
  );

  return array();
}

function widget_facebook_embed_homepage() {
	drupal_add_js(drupal_get_path('module','widget_facebook').'/assets/widget_facebook.js');
	return theme('widget_facebook_box');	
}