<?php

/*
 * implements hook_theme
 */
function widget_supporter_theme($existing, $type, $theme, $path) {
	return array(
		'widget_supporter' => array(
			'template' => 'templates/widget-supporter',
			'variables' => array (
				'logos' => null
			)
		),
	);
	
}

function widget_supporter_embed() {
	drupal_add_js(drupal_get_path('module', 'widget_supporter') . '/assets/widget_supporter.js');
	$logos = views_embed_view('nodequeue_supporter_list');
	
	return theme('widget_supporter',array('logos' => $logos));
}
